version: "3"
services:
  stg:
    build: .
    image: ioc_staging
    container_name: ioc-stg
    tty: true
    environment: 
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-hogehoge}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-hogehoge}
    volumes: 
      - ./terraform/stg:/infra/terraform